name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"
      - name: Install dependencies
        run: |
          uv sync --dev
      - name: Run quality checks
        run: |
          python quality.py format
          python quality.py lint
          python quality.py type
          python quality.py security
      - name: Run tests with coverage
        env:
          PYTHONPATH: src
          INVENTORY_APP_DIR: ${{ runner.temp }}/inventory-home
          INVENTORY_AUDIT_DISABLED: '1'
          INVENTORY_DEV_MODE: 'true'
        run: |
          python quality.py test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
        continue-on-error: true

  integration:
    needs: [quality]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"
      - name: Install dependencies
        run: |
          uv sync --dev
      - name: Start application
        run: |
          uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 10
      - name: Run integration tests
        env:
          PYTHONPATH: src
          INVENTORY_APP_DIR: ${{ runner.temp }}/inventory-home
          INVENTORY_AUDIT_DISABLED: '1'
          INVENTORY_DEV_MODE: 'true'
        run: |
          python -m pytest tests/ -v
