name: Release (PyInstaller onefile)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Backend deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi "uvicorn[standard]" sqlmodel openpyxl jinja2 python-multipart httpx pyinstaller
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
      - name: Build onefile
        run: |
          pyinstaller inventory-app.spec
      - name: Upload artifact (workflow artifact)
        uses: actions/upload-artifact@v4
        with:
          name: inventory-app-${{ runner.os }}
          path: dist/**
      - name: Attach artifacts to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
